export const teamsId = {
  "Real Madrid": 86,
  Barcelona: 83,
  "Athletico Madrid": 1068,
  "Real Sociedad": 89,
  "Athletic Club": 93,
  "Real Betis": 244,
  Osasuna: 97,
  Villareal: 102,
  "Rayo Vallecano": 101,
  Valencia: 94,
  "Real Valladolid": 95,
  Mallorca: 84,
  Almeria: 102,
  Espanyol: 88,
  "Celta Vigo": 85,
  Girona: 9812,
  Getafe: 2922,
  Sevilla: 243,
  Cadiz: 3842,
  Elche: 3751,
  Arsenal: 359,
  "Manchester City": 382,
  "Tottenham Hotspur": 367,
  "NewCastle United": 361,
  "Manchester United": 360,
  Chelsea: 363,
  Fulham: 370,
  "Brighton Hove Albion": 331,
  Liverpool: 364,
  "Crystal Palace": 384,
  Brentford: 337,
  Everton: 368,
  "West Ham United": 371,
  "AFC Bournemouth": 349,
  "Leeds United": 357,
  "Aston Villa": 362,
  Southampton: 376,
  "Leicester City": 375,
  "Wolverhampton Wanderers": 380,
  "Nottingham Forest": 393,
};

export const teamsInfo = [
  ["Real Madrid", "https://media-5.api-sports.io/football/teams/541.png", 1],
  ["Barcelona", "https://media-5.api-sports.io/football/teams/529.png", 2],
  ["Real Sociedad", "https://media-4.api-sports.io/football/teams/548.png", 3],
  ["Athletic Club", "https://media-5.api-sports.io/football/teams/531.png", 4],
  [
    "Atletico Madrid",
    "https://media-4.api-sports.io/football/teams/530.png",
    5,
  ],
  ["Real Betis", "https://media-5.api-sports.io/football/teams/543.png", 6],
  ["Osasuna", "https://media-4.api-sports.io/football/teams/727.png", 7],
  ["Rayo Vallecano", "https://media-5.api-sports.io/football/teams/728.png", 8],
  ["Villarreal", "https://media-6.api-sports.io/football/teams/533.png", 9],
  ["Valencia", "https://media-5.api-sports.io/football/teams/532.png", 10],
  ["Mallorca", "https://media-5.api-sports.io/football/teams/798.png", 11],
  ["Valladolid", "https://media-6.api-sports.io/football/teams/720.png", 12],
  ["Girona", "https://media-5.api-sports.io/football/teams/547.png", 13],
  ["Almeria", "https://media-4.api-sports.io/football/teams/723.png", 14],
  ["Getafe", "https://media-4.api-sports.io/football/teams/546.png", 15],
  ["Espanyol", "https://media-5.api-sports.io/football/teams/540.png", 16],
  ["Celta Vigo", "https://media-4.api-sports.io/football/teams/538.png", 17],
  ["Sevilla", "https://media-4.api-sports.io/football/teams/536.png", 18],
  ["Cadiz", "https://media-4.api-sports.io/football/teams/724.png", 19],
  ["Elche", "https://media-5.api-sports.io/football/teams/797.png", 20],
  ["Arsenal", "https://media-5.api-sports.io/football/teams/42.png", 21],
  [
    "Manchester City",
    "https://media-4.api-sports.io/football/teams/50.png",
    22,
  ],
  ["Newcastle", "https://media-4.api-sports.io/football/teams/34.png", 23],
  ["Tottenham", "https://media-6.api-sports.io/football/teams/47.png", 24],
  [
    "Manchester United",
    "https://media-5.api-sports.io/football/teams/33.png",
    25,
  ],
  ["Liverpool", "https://media-4.api-sports.io/football/teams/40.png", 26],
  ["Brighton", "https://media-6.api-sports.io/football/teams/51.png", 27],
  ["Chelsea", "https://media-6.api-sports.io/football/teams/49.png", 28],
  ["Fulham", "https://media-4.api-sports.io/football/teams/36.png", 29],
  ["Brentford", "https://media-5.api-sports.io/football/teams/55.png", 30],
  ["Crystal Palace", "https://media-4.api-sports.io/football/teams/52.png", 31],
  ["Aston Villa", "https://media-6.api-sports.io/football/teams/66.png", 32],
  ["Leicester", "https://media-4.api-sports.io/football/teams/46.png", 33],
  ["Bournemouth", "https://media-5.api-sports.io/football/teams/35.png", 34],
  ["Leeds", "https://media-6.api-sports.io/football/teams/63.png", 35],
  ["West Ham", "https://media-6.api-sports.io/football/teams/48.png", 36],
  ["Everton", "https://media-5.api-sports.io/football/teams/45.png", 37],
  [
    "Nottingham Forest",
    "https://media-6.api-sports.io/football/teams/65.png",
    38,
  ],
  ["Southampton", "https://media-4.api-sports.io/football/teams/41.png", 39],
  ["Wolves", "https://media-4.api-sports.io/football/teams/39.png", 40],
  ["Napoli", "https://media-5.api-sports.io/football/teams/492.png", 41],
  ["Ajax", "https://media-5.api-sports.io/football/teams/194.png", 42],
  ["Rangers", "https://media-6.api-sports.io/football/teams/257.png", 43],
  ["FC Porto", "https://media-5.api-sports.io/football/teams/212.png", 44],
  [
    "Club Brugge KV",
    "https://media-4.api-sports.io/football/teams/569.png",
    45,
  ],
  [
    "Bayer Leverkusen",
    "https://media-4.api-sports.io/football/teams/168.png",
    46,
  ],
  ["Bayern Munich", "https://media-5.api-sports.io/football/teams/157.png", 47],
  ["Inter", "https://media-5.api-sports.io/football/teams/505.png", 48],
  ["Plzen", "https://media-5.api-sports.io/football/teams/567.png", 49],
  [
    "Eintracht Frankfurt",
    "https://media-6.api-sports.io/football/teams/169.png",
    50,
  ],
  ["Sporting CP", "https://media-5.api-sports.io/football/teams/228.png", 51],
  ["Marseille", "https://media-4.api-sports.io/football/teams/81.png", 52],
  ["AC Milan", "https://media-5.api-sports.io/football/teams/489.png", 53],
  [
    "Red Bull Salzburg",
    "https://media-4.api-sports.io/football/teams/571.png",
    54,
  ],
  ["Dinamo Zagreb", "https://media-6.api-sports.io/football/teams/620.png", 55],
  ["RB Leipzig", "https://media-5.api-sports.io/football/teams/173.png", 56],
  [
    "Shakhtar Donetsk",
    "https://media-5.api-sports.io/football/teams/550.png",
    57,
  ],
  ["Celtic", "https://media-5.api-sports.io/football/teams/247.png", 58],
  [
    "Borussia Dortmund",
    "https://media-4.api-sports.io/football/teams/165.png",
    59,
  ],
  ["FC Copenhagen", "https://media-5.api-sports.io/football/teams/400.png", 60],
  ["Benfica", "https://media-6.api-sports.io/football/teams/211.png", 61],
  [
    "Paris Saint Germain",
    "https://media-5.api-sports.io/football/teams/85.png",
    62,
  ],
  ["Juventus", "https://media-6.api-sports.io/football/teams/496.png", 63],
  [
    "Maccabi Haifa",
    "https://media-6.api-sports.io/football/teams/4195.png",
    64,
  ],
  [
    "America",
    "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/227.png&h=200&w=200",
    65,
  ],
];
